nomaya_social:
  buttons:
    facebook:
      url:            null
      locale:         "fr_FR"
      send:           false
      width:          300
      showFaces:      false
      layout:         "button_count"
    twitter:
      url:            null
      locale:         "fr"
      message:        "Je veux partager ça avec vous"
      text:           "Tweet"
      via:            "L'Equipe cartedevisitevirtuelle.fr"
      tag:            "ttot"
    googleplus:
      url:            null
      locale :        "fr"
      size :          "medium"
      annotation :    "bubble"
      width :         300
    linkedin:
      url:            null
      locale:         "fr_FR"
      counter:        "right"
    pinterest:
      url:            null
  links:
    facebook:           "http://www.facebook.com/yann.chauvel"
    googleplus:         "https://plus.google.com/105931415830389032796"
  theme:                  'default' # optional