<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1QbJLIG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1QbJLIG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1QbJLIG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1QbJLIG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1QbJLIG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1QbJLIG',
    'container.build_id' => '667601f9',
    'container.build_time' => 1648816645,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1QbJLIG');
