<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPTPjddC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPTPjddC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPTPjddC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPTPjddC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPTPjddC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PTPjddC',
    'container.build_id' => 'fef98e27',
    'container.build_time' => 1646840009,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPTPjddC');
